### ISSUE TITLE
bug with using pracpac on an R package with no dependencies

### ISSUE THREAD

**Issue by vpnagraj** [signaturescience/pracpac#91]
right now if you try to use `pracpac` templating on an R package with no dependencies, the following error will get raised:

```
use_docker()
```

```
Error in strsplit(as.data.frame(read.dcf(descfile), stringsAsFactors = FALSE)$Imports, : 
non-character argument
```
pretty sure that is coming from `pkg_info()` step being unable to split the "Imports" in DESCRIPTION because it isn't there:

```
pkg_info()
```

```
Error in strsplit(as.data.frame(read.dcf(descfile), stringsAsFactors = FALSE)$Imports, : 
non-character argument
```

you *could* hack the DESCRIPTION to get this working by changing:

```
Package: nodeps
Type: Package
Title: What the Package Does (Title Case)
Version: 0.1.0
Author: Who wrote it
Maintainer: The package maintainer <yourself@somewhere.net>
Description: More about what it does (maybe more than one line)
    Use four spaces when indenting paragraphs within the Description.
License: What license is it under?
Encoding: UTF-8
LazyData: true
```

to 

```
Package: nodeps
Type: Package
Title: What the Package Does (Title Case)
Version: 0.1.0
Author: Who wrote it
Maintainer: The package maintainer <yourself@somewhere.net>
Description: More about what it does (maybe more than one line)
    Use four spaces when indenting paragraphs within the Description.
License: What license is it under?
Encoding: UTF-8
LazyData: true
Imports:
```

but i think we should fix it so thats not necessary.

**Comment by stephenturner** [comment]
This one's not as easy as I thought it'd be. I can fix `pkg_info()` to return a NULL or NA or "" or whatever if the Imports is empty. 

```r
# From this:
  # Get package dependencies
  pkgdeps <- strsplit(as.data.frame(read.dcf(descfile),stringsAsFactors=FALSE)$Imports, split=",\\n")[[1]]

## To this
  # Get package dependencies
  imports <- as.data.frame(read.dcf(descfile),stringsAsFactors=FALSE)$Imports
  if (is.null(imports)) {
    pkgdeps <- NULL
  } else {
    pkgdeps <- strsplit(, split=",\\n")[[1]]
  }
```

And, later when parsing this vector to turn it into a string, I could also make this NA or NULL or whatever

```r
  # Turn the string vector: c("a", "b", "c") to the single element string "'a','b','c'"
  pkgs <- paste(paste0("'",info$pkgdeps,"'"), collapse=",")

# conditional logic to make pkgs NULL if info$pkgdeps is NULL
```

However, later this thing is getting glued into the dockerfile template when not using renv:

```r
  base_dockerfile <- glue::glue(base_template, base_image = base_image, pkgs = pkgs, pkgname=info$pkgname, pkgver=info$pkgver, repos = repos)
```

And the Dockerfile template: 

```
RUN Rscript -e "BiocManager::install(c({pkgs}), update=FALSE, ask=FALSE)"
```

So, if there are no packages, the build would fail if we passed in a NULL or NA or "" or anything else here. 

This problem also touches renv. The original pkgdeps vector must have _something_ in it.

```r
  renv::snapshot(project = tempdir(), packages = c(info$pkgdeps, other_packages), lockfile = out_path, prompt = FALSE, update = TRUE)
```

One way to tackle this problem is to conditionally use a different base template depending on the contents of the pkgdeps, conditionally running different renv snapshot commands depending on pkgdeps contents, probably some other conditional handling elsewhere that I haven't yet found. This could get ugly quickly.

An alternative that could solve this problem is to install a package. Any package. If pkgdeps is null, somewhere where it's encountered in add_dockerfile and renv_deps, to install _something_. R6 has no deps and is only 80kb. You could install stats or utils, but you get a warning that you shouldn't install a base package. Or a data package. palmerpenguins.

Thoughts?
